kuponobot:
  consumer_key: U4xpQRL2S1f3PQRrX34yw
  consumer_secret: azDmWtflLFT2h68vefQB0tuFPRUMuxSh00ie4hBFHDo
  oauth_token: 358337728-ftAINzTj5YFgMu1AiBnnYcH7FHHvfeDpliz5Ew8z
  oauth_token_secret: 7F36kVSJb6aIHMaq0vndgspvJreRSIFqjIxfGFHk6s